blank_issues_enabled: false
contact_links:
  - name: WoW-Mania Community Forum
    url: https://wow-mania.com/forum/
    about: Please ask and answer questions here.
  - name: WoW-Mania Suggestions
    url: https://wow-mania.com/forum/viewforum.php?f=11&sid=7693b7cdd7439836ee2ac7d721de4a25
    about: Please make any suggestions you may have here.
  - name: Connection issues
    url: https://wow-mania.com/forum/viewtopic.php?f=13&t=9
    about: Please read this guide for connection issues.
